// This file is autogenerated
using System;
using System.Runtime.InteropServices;

#if UNITY_2020_2_OR_NEWER
#nullable enable
#endif

namespace AUTD3Sharp
{
    namespace NativeMethods
    {
        internal static class GeometryViewer
        {
            private const string DLL = "autd3capi_geometry_viewer";

            [DllImport(DLL, CallingConvention = CallingConvention.Cdecl)] public static extern GeometryViewerPtr AUTDGeometryViewer();

            [DllImport(DLL, CallingConvention = CallingConvention.Cdecl)] public static extern GeometryViewerPtr AUTDGeometryViewerSize(GeometryViewerPtr viewer, uint width, uint height);

            [DllImport(DLL, CallingConvention = CallingConvention.Cdecl)] public static extern GeometryViewerPtr AUTDGeometryViewerVsync(GeometryViewerPtr viewer, [MarshalAs(UnmanagedType.U1)] bool vsync);

            [DllImport(DLL, CallingConvention = CallingConvention.Cdecl)] public static extern int AUTDGeometryViewerRun(GeometryViewerPtr viewer, GeometryPtr geometry);
        }
    }

    [StructLayout(LayoutKind.Sequential)]
    public struct GeometryViewerPtr
    {
        public IntPtr _0;
    }

}

#if UNITY_2020_2_OR_NEWER
#nullable disable
#endif


