[package]
name = "autd3-link-soem"
version = "8.4.0"
authors = ["shun suzuki <suzuki@hapis.k.u-tokyo.ac.jp>"]
edition = "2021"

license-file = "LICENSE"
description = "Link of AUTD using SOEM."
repository = "https://github.com/shinolab/autd3"
readme = "README.md"
keywords = ["autd"]

[build-dependencies]
bindgen = "0.64.0"
cc = { version = "1.0.73", features = ["parallel"] }
glob = "0.3.0"

[dependencies]
anyhow = "1.0.57"
autd3-core = {path="../autd3-core", version="8.4.0"}
autd3-timer = {path="../autd3-timer", version="8.4.0"}
crossbeam-channel = "0.5.4"
libc = "0.2.124"
thiserror = "1.0.30"

[target.'cfg(windows)'.dependencies]
windows = {version = "0.46.0", features = ["Win32_Foundation", "Win32_System_Performance", "Win32_Networking_WinSock", "Win32_System_SystemInformation"]}
once_cell = "1.10.0"
