[package]
name = "autd3capi-link-simulator"
version = "12.2.0"
edition = "2021"
license = "MIT"

[lib]
crate-type = ["cdylib"]

[dependencies]
autd3capi-def = {path="../autd3capi-def", version="12.2.0"}
autd3-link-simulator = {path="../../src/autd3-link-simulator", version="12.2.0"}

[build-dependencies]
wrapper-generator = {path="../wrapper-generator"}
