[package]
name = "autd3capi-link-simulator"
version = "14.2.1"
edition = "2021"
license = "MIT"

[lib]
crate-type = ["cdylib"]

[dependencies]
autd3capi-def = { path = "../autd3capi-def", version = "14.2.1" }
autd3-link-simulator = { path = "../../src/autd3-link-simulator", version = "14.2.1" }

[build-dependencies]
wrapper-generator = { path = "../wrapper-generator" }
