[package]
name = "autd3capi-link-simulator"
version = "10.0.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
autd3capi-common = {path="../autd3capi-common", version="10.0.0"}
autd3 = {path="../../src/autd3", version="10.0.0"}
autd3-core = {path="../../src/autd3-core", version="10.0.0"}
autd3-link-simulator = {path="../../src/autd3-link-simulator", version="10.0.0"}
libc = "0.2.144"

[build-dependencies]
wrapper-generator = {path="../wrapper-generator"}
