[package]
name = "simulator"
version = "14.2.1"
edition = "2021"
authors = ["shun suzuki <suzuki@hapis.k.u-tokyo.ac.jp>"]

license = "MIT"
description = "AUTD Simulator"
repository = "https://github.com/shinolab/autd3"
keywords = ["autd"]

[dependencies]
anyhow = "1.0.71"
autd3-simulator = { path = "../../src/autd3-simulator", version = "14.2.1" }
clap = { version = "4.3.0", features = ["derive"] }
serde_json = "1.0.96"
spdlog-rs = "0.3.8"

[features]
use_meter = ["autd3-simulator/use_meter"]
left_handed = ["autd3-simulator/left_handed"]
