[package]
name = "autd3-simulator"
version = "14.2.0"
authors = ["shun suzuki <suzuki@hapis.k.u-tokyo.ac.jp>"]
edition = "2021"

license = "MIT"
description = "AUTD Simulator"
repository = "https://github.com/shinolab/autd3"
readme = "README.md"
keywords = ["autd"]

[dependencies]
autd3-core = { path = "../autd3-core", version = "14.2.0" }
autd3-firmware-emulator = { path = "../autd3-firmware-emulator", version = "14.2.0" }
autd3-protobuf = { path = "../autd3-protobuf", version = "14.2.0" }
bitflags = "2.3.1"
bytemuck = { version = "1.13.1", features = ["derive", "extern_crate_std", "min_const_generics"] }
camera_controllers = "0.33.0"
cgmath = "0.18.0"
png = "0.17.8"
imgui = "0.11.0"
imgui-winit-support = "0.11.0"
scarlet = "~1.1.0"
serde = { version = "1.0.174", features = ["derive"] }
vulkano = "0.33.0"
vulkano-shaders = "0.33.0"
vulkano-win = "0.33.0"
winit = "0.28.6"
spdlog-rs = "0.3.8"
crossbeam-channel = "0.5.8"
image = "0.24.6"
tokio = { version = "1.0", features = ["rt-multi-thread"] }
futures-util = "0.3.28"
tonic = "0.9.2"
anyhow = "1.0.71"

[features]
default = []
use_meter = ["autd3-core/use_meter"]
left_handed = []
enable_debug = []
