[package]
name = "autd3-simulator"
version = "10.0.0"
authors = ["shun suzuki <suzuki@hapis.k.u-tokyo.ac.jp>"]
edition = "2021"

license-file = "LICENSE"
description = "AUTD Simulator"
repository = "https://github.com/shinolab/autd3"
readme = "../README.md"
keywords = ["autd"]

[dependencies]
autd3-core = {path="../autd3-core", version="10.0.0"}
autd3-firmware-emulator = {path="../autd3-firmware-emulator", version="10.0.0"}
bitflags = "2.3.1"
bytemuck = { version = "1.13.1", features = ["derive", "extern_crate_std", "min_const_generics"] }
camera_controllers = "0.33.0"
cgmath = "0.18.0"
imgui = { git = "https://github.com/imgui-rs/imgui-rs.git", rev = "refs/pull/716/head" } # for winit 0.28
imgui-winit-support = { git = "https://github.com/imgui-rs/imgui-rs.git", rev = "refs/pull/716/head" } # for winit 0.28
png = "0.17.8"
scarlet = "1.1.0"
serde = "1.0.163"
vulkano = "0.33.0"
vulkano-shaders = "0.33.0"
vulkano-win = "0.33.0"
winit = "0.28.6"
imgui-vulkano-renderer = { git = "https://github.com/sssssssuzuki/imgui-vulkano-renderer.git", branch = "vulkano-0.33.0" }
spdlog-rs = "0.3.8"
crossbeam-channel = "0.5.8"
anyhow = "1.0.71"
serde_derive = "1.0.163"

[features]
default = []
use_meter = []
left_handed = []
enable_debug = []
