[package]
name = "autd3-timer"
version = "8.4.1"
authors = ["shun suzuki <suzuki@hapis.k.u-tokyo.ac.jp>"]
edition = "2021"

license = "MIT"
description = "Native timer wrapper."
repository = "https://github.com/shinolab/autd3"
readme = "README.md"
keywords = ["autd"]
exclude = [
    ".github/*",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
cc = "1.0.72"

[dependencies]
libc = "0.2.112"
thiserror = "1.0.30"

[target.'cfg(windows)'.dependencies]
windows = {version = "0.46.0", features = ["Win32_Media_Multimedia", "Win32_System_Threading", "Win32_Foundation"]}
