[package]
name = "autd3-core"
version = "2.7.2"
authors = ["shun suzuki <suzuki@hapis.k.u-tokyo.ac.jp>"]
edition = "2021"

license-file = "LICENSE"
description = "Core functions of AUTD3"
repository = "https://github.com/shinolab/autd3"
readme = "README.md"
keywords = ["autd"]

[dependencies]
anyhow = "1.0.57"
autd3-driver = {path = "../autd3-driver", version="2.7.2"}
bitflags = "1.3.2"
itertools = "0.10.3"
nalgebra = "0.31.0"
thiserror = "1.0.30"
