// This file is autogenerated
using System;
using System.Runtime.InteropServices;

#if UNITY_2020_2_OR_NEWER
#nullable enable
#endif

namespace AUTD3Sharp
{
    namespace NativeMethods
    {
        internal static class ModulationAudioFile
        {
            private const string DLL = "autd3capi_modulation_audio_file";

            [DllImport(DLL, CallingConvention = CallingConvention.Cdecl)] public static extern IntPtr AUTDModulationWav(string path, byte[] err);
        }
    }

}

#if UNITY_2020_2_OR_NEWER
#nullable disable
#endif


