[package]
name = "autd3capi"
version = "10.0.0"
edition = "2021"

[lib]
crate-type = ["lib", "cdylib", "staticlib"]

[dependencies]
autd3capi-common = {path="../autd3capi-common", version="10.0.0"}
autd3 = {path="../../src/autd3", version="10.0.0"}
autd3-core = {path="../../src/autd3-core", version="10.0.0"}
autd3-traits = {path="../../src/autd3-traits", version="10.0.0"}
libc = "0.2.144"

[build-dependencies]
wrapper-generator = {path="../wrapper-generator"}

[features]
single_float = ["autd3capi-common/single_float"]
use_meter = ["autd3capi-common/use_meter"]
parallel = ["autd3capi-common/parallel"]
