[package]
name = "autd3capi"
version = "10.0.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
autd3 = {path="../../rust/autd3", version="10.0.0", features=["dynamic"]}
autd3-core = {path="../../rust/autd3-core", version="10.0.0", features=["dynamic"]}
autd3-traits = {path="../../rust/autd3-traits", version="10.0.0"}
libc = "0.2.144"

[features]
default = ["dynamic"]
dynamic = []
single_float = ["autd3/single_float"]
use_meter = ["autd3/use_meter"]
parallel = ["autd3/parallel"]
