[package]
name = "autd3capi"
version = "11.0.1"
edition = "2021"
license = "MIT"

[lib]
crate-type = ["lib", "cdylib", "staticlib"]

[dependencies]
autd3capi-def = {path="../autd3capi-def", version="11.0.1"}
autd3-core = {path="../../src/autd3-core", version="11.0.1"}

[build-dependencies]
wrapper-generator = {path="../wrapper-generator"}

[features]
single_float = ["autd3capi-def/single_float", "autd3-core/single_float"]
use_meter = ["autd3capi-def/use_meter", "autd3-core/use_meter"]
parallel = ["autd3capi-def/parallel", "autd3-core/parallel"]
