[package]
name = "autd3-link-simulator"
version = "8.3.0"
authors = ["shun suzuki <suzuki@hapis.k.u-tokyo.ac.jp>"]
edition = "2021"

license-file = "LICENSE"
description = "Link for autd-simulator"
repository = "https://github.com/shinolab/autd3"
readme = "README.md"
keywords = ["autd"]

[dependencies]
anyhow = "1.0.57"
autd3-core = {path="../autd3-core", version="8.3.0"}
smem = "0.1.0"
thiserror = "1.0.30"
