// <auto-generated>
// This code is generated by csbindgen.
// DON'T CHANGE THIS DIRECTLY.
// </auto-generated>
#pragma warning disable CS8500
#pragma warning disable CS8981
using System;
using System.Runtime.InteropServices;


namespace AUTD3Sharp
{
    internal static unsafe partial class NativeMethodsDef
    {
        const string __DllName = "autd3capi_def";

        internal const uint NUM_TRANS_IN_UNIT = 249;
        internal const uint NUM_TRANS_IN_X = 18;
        internal const uint NUM_TRANS_IN_Y = 14;
        internal const float TRANS_SPACING_MM = 10.16f;
        internal const float DEVICE_HEIGHT_MM = 151.4f;
        internal const float DEVICE_WIDTH_MM = 192f;
        internal const uint FPGA_CLK_FREQ = 20480000;
        internal const float ULTRASOUND_FREQUENCY = 40000f;
        internal const int AUTD3_TRUE = 1;
        internal const int AUTD3_FALSE = 0;



    }



}
    