// <auto-generated>
// This code is generated by csbindgen.
// DON'T CHANGE THIS DIRECTLY.
// </auto-generated>
#pragma warning disable CS8500
#pragma warning disable CS8981
using System;
using System.Runtime.InteropServices;


namespace AUTD3Sharp.NativeMethods
{
    public static unsafe partial class NativeMethodsLinkTwinCAT
    {
        const string __DllName = "autd3capi_link_twincat";



        [DllImport(__DllName, EntryPoint = "AUTDLinkTwinCAT", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern LinkTwinCATBuilderPtr AUTDLinkTwinCAT();

        [DllImport(__DllName, EntryPoint = "AUTDLinkTwinCATWithTimeout", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern LinkTwinCATBuilderPtr AUTDLinkTwinCATWithTimeout(LinkTwinCATBuilderPtr twincat, ulong timeout_ns);

        [DllImport(__DllName, EntryPoint = "AUTDLinkTwinCATIntoBuilder", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern LinkBuilderPtr AUTDLinkTwinCATIntoBuilder(LinkTwinCATBuilderPtr twincat);

        [DllImport(__DllName, EntryPoint = "AUTDLinkRemoteTwinCAT", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern ResultLinkRemoteTwinCATBuilder AUTDLinkRemoteTwinCAT(byte* server_ams_net_id);

        [DllImport(__DllName, EntryPoint = "AUTDLinkRemoteTwinCATWithServerIP", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern LinkRemoteTwinCATBuilderPtr AUTDLinkRemoteTwinCATWithServerIP(LinkRemoteTwinCATBuilderPtr twincat, byte* addr);

        [DllImport(__DllName, EntryPoint = "AUTDLinkRemoteTwinCATWithClientAmsNetId", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern LinkRemoteTwinCATBuilderPtr AUTDLinkRemoteTwinCATWithClientAmsNetId(LinkRemoteTwinCATBuilderPtr twincat, byte* id);

        [DllImport(__DllName, EntryPoint = "AUTDLinkRemoteTwinCATWithTimeout", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern LinkRemoteTwinCATBuilderPtr AUTDLinkRemoteTwinCATWithTimeout(LinkRemoteTwinCATBuilderPtr twincat, ulong timeout_ns);

        [DllImport(__DllName, EntryPoint = "AUTDLinkRemoteTwinCATIntoBuilder", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern LinkBuilderPtr AUTDLinkRemoteTwinCATIntoBuilder(LinkRemoteTwinCATBuilderPtr twincat);


    }

    [StructLayout(LayoutKind.Sequential)]
    public unsafe partial struct LinkTwinCATBuilderPtr
    {
        public IntPtr Item1;
    }

    [StructLayout(LayoutKind.Sequential)]
    public unsafe partial struct LinkRemoteTwinCATBuilderPtr
    {
        public IntPtr Item1;
    }

    [StructLayout(LayoutKind.Sequential)]
    public unsafe partial struct ResultLinkRemoteTwinCATBuilder
    {
        public LinkRemoteTwinCATBuilderPtr result;
        public uint err_len;
        public IntPtr err;
    }



}
    