// <auto-generated>
// This code is generated by csbindgen.
// DON'T CHANGE THIS DIRECTLY.
// </auto-generated>
#pragma warning disable CS8500
#pragma warning disable CS8981
using System;
using System.Runtime.InteropServices;


namespace AUTD3Sharp
{
    internal static unsafe partial class NativeMethodsLinkSimulator
    {
        const string __DllName = "autd3capi_link_simulator";



        [DllImport(__DllName, EntryPoint = "AUTDLinkSimulator", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern LinkSimulatorBuilderPtr AUTDLinkSimulator(ushort port);

        [DllImport(__DllName, EntryPoint = "AUTDLinkSimulatorWithAddr", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern LinkSimulatorBuilderPtr AUTDLinkSimulatorWithAddr(LinkSimulatorBuilderPtr simulator, byte* addr, byte* err);

        [DllImport(__DllName, EntryPoint = "AUTDLinkSimulatorWithTimeout", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern LinkSimulatorBuilderPtr AUTDLinkSimulatorWithTimeout(LinkSimulatorBuilderPtr simulator, ulong timeout_ns);

        [DllImport(__DllName, EntryPoint = "AUTDLinkSimulatorIntoBuilder", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern LinkBuilderPtr AUTDLinkSimulatorIntoBuilder(LinkSimulatorBuilderPtr simulator);

        [DllImport(__DllName, EntryPoint = "AUTDLinkSimulatorUpdateGeometry", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int AUTDLinkSimulatorUpdateGeometry(LinkPtr simulator, GeometryPtr geometry, byte* err);


    }

    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct LinkSimulatorBuilderPtr
    {
        public IntPtr Item1;
    }



}
    