[package]
name = "doc_checker"
version = "2.7.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.57"
regex = "1.5.6"
capi_header_parser = {path = "../capi_header_parser"}
