[package]
name = "autd3-examples"
version = "2.7.2"
authors = ["shun suzuki <suzuki@hapis.k.u-tokyo.ac.jp>"]
edition = "2021"

[[bin]]
name = "soem"
path = "src/soem.rs"
required-features = ["soem"]

[[bin]]
name = "twincat"
path = "src/twincat.rs"
required-features = ["twincat"]

[[bin]]
name = "simulator"
path = "src/simulator.rs"
required-features = ["simulator"]

[dependencies]
anyhow = "1.0.57"
autd3 = {path="../autd3"}
autd3-gain-holo = {path="../autd3-gain-holo", version="2.7.2"}
autd3-link-simulator = {path="../autd3-link-simulator", optional = true, version="2.7.2"}
autd3-link-soem = {path="../autd3-link-soem", optional = true, version="2.7.2"}
autd3-link-twincat = {path="../autd3-link-twincat", optional = true, version="2.7.2"}
colored = "2.0.0"

[features] 
default = []
simulator = ["autd3-link-simulator"]
soem = ["autd3-link-soem"]
twincat = ["autd3-link-twincat"]
all = ["soem", "twincat", "simulator"]
