[package]
name = "autd3-examples"
version = "10.0.0"
authors = ["shun suzuki <suzuki@hapis.k.u-tokyo.ac.jp>"]
edition = "2021"

[[bin]]
name = "debug"
path = "src/debug.rs"

[[bin]]
name = "soem"
path = "src/soem.rs"
required-features = ["soem"]

[[bin]]
name = "remote_soem"
path = "src/remote_soem.rs"
required-features = ["soem"]

[[bin]]
name = "twincat"
path = "src/twincat.rs"
required-features = ["twincat"]

[[bin]]
name = "simulator"
path = "src/simulator.rs"
required-features = ["simulator"]

[dependencies]
anyhow = "1.0.57"
autd3 = {path="../autd3"}
autd3-gain-holo = {path="../autd3-gain-holo", version="10.0.0"}
autd3-link-simulator = {path="../autd3-link-simulator", optional = true, version="10.0.0"}
autd3-link-soem = {path="../autd3-link-soem", optional = true, version="10.0.0"}
autd3-link-twincat = {path="../autd3-link-twincat", optional = true, version="10.0.0"}
autd3-modulation-audio-file = {path="../autd3-modulation-audio-file", version="10.0.0"}
colored = "2.0.0"

[features] 
default = []
simulator = ["autd3-link-simulator"]
soem = ["autd3-link-soem"]
twincat = ["autd3-link-twincat"]
all = ["soem", "twincat", "simulator"]
