[package]
name = "autd3-link-monitor"
version = "13.0.0"
authors = ["shun suzuki <suzuki@hapis.k.u-tokyo.ac.jp>"]
edition = "2021"

license = "MIT"
description = "Link for monitoring"
repository = "https://github.com/shinolab/autd3"
readme = "README.md"
keywords = ["autd"]

[dependencies]
autd3-firmware-emulator = {path="../autd3-firmware-emulator", version="13.0.0"}
autd3-core = {path="../autd3-core", version="13.0.0"}
thiserror = "1.0.30"
pyo3 = { version = "0.19.0", features = ["auto-initialize"], optional = true }
which = "4.4.0"
itertools = "0.11.0"
vulkano = { version = "0.33.0", optional = true }
vulkano-shaders = { version = "0.33.0", optional = true }
plotters = "0.3.5"

[features]
default = []
python = ["pyo3"]
gpu = ["vulkano", "vulkano-shaders"]
single_float = ["autd3-core/single_float"]
