[package]
name = "autd3capi-common"
version = "10.0.0"
edition = "2021"

[dependencies]
autd3 = {path="../../rust/autd3", version="10.0.0"}
libc = "0.2.144"

[features]
single_float = ["autd3/single_float"]
use_meter = ["autd3/use_meter"]
parallel = ["autd3/parallel"]
