[package]
name = "autd3capi-def"
version = "12.2.0"
edition = "2021"
license = "MIT"

[lib]
crate-type = ["rlib", "cdylib", "staticlib"]

[dependencies]
autd3capi-common = {path="../autd3capi-common", version="12.2.0"}

[build-dependencies]
wrapper-generator = {path="../wrapper-generator"}

[features]
single_float = ["autd3capi-common/single_float"]
use_meter = ["autd3capi-common/use_meter"]
parallel = ["autd3capi-common/parallel"]
