[package]
name = "autd3-driver"
version = "9.0.1"
authors = ["shun suzuki <suzuki@hapis.k.u-tokyo.ac.jp>"]
edition = "2021"

license-file = "LICENSE"
description = "AUTD3 driver"
repository = "https://github.com/shinolab/autd3"
readme = "README.md"
keywords = ["autd"]

[dependencies]
anyhow = "1.0.57"
bitflags = "2.0.2"
num = "0.4.0"
thiserror = "1.0.31"

[dev-dependencies]
rand = "0.8.5"
assert_approx_eq = "1.1.0"
