[package]
name = "autd3-demo-tui"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.72"
argh = "0.1.10"
autd3 = { path = "../../src/autd3" }
crossterm = "0.27.0"
rand = "0.8.5"
ratatui = { version = "0.23.0", features = ["all-widgets"] }
