// This file is autogenerated
using System;
using System.Runtime.InteropServices;

#if UNITY_2020_2_OR_NEWER
#nullable enable
#endif

namespace AUTD3Sharp
{
    namespace NativeMethods
    {
        internal static class LinkTwinCAT
        {
            private const string DLL = "autd3capi_link_twincat";

            [DllImport(DLL, CallingConvention = CallingConvention.Cdecl)] public unsafe static extern LinkTwinCATBuilderPtr AUTDLinkTwinCAT();

            [DllImport(DLL, CallingConvention = CallingConvention.Cdecl)] public unsafe static extern LinkTwinCATBuilderPtr AUTDLinkTwinCATWithTimeout(LinkTwinCATBuilderPtr twincat, ulong timeoutNs);

            [DllImport(DLL, CallingConvention = CallingConvention.Cdecl)] public unsafe static extern LinkBuilderPtr AUTDLinkTwinCATIntoBuilder(LinkTwinCATBuilderPtr twincat);

            [DllImport(DLL, CallingConvention = CallingConvention.Cdecl)] public unsafe static extern LinkRemoteTwinCATBuilderPtr AUTDLinkRemoteTwinCAT(string serverAmsNetId, byte[] err);

            [DllImport(DLL, CallingConvention = CallingConvention.Cdecl)] public unsafe static extern LinkRemoteTwinCATBuilderPtr AUTDLinkRemoteTwinCATWithServerIP(LinkRemoteTwinCATBuilderPtr twincat, string addr);

            [DllImport(DLL, CallingConvention = CallingConvention.Cdecl)] public unsafe static extern LinkRemoteTwinCATBuilderPtr AUTDLinkRemoteTwinCATWithClientAmsNetId(LinkRemoteTwinCATBuilderPtr twincat, string id);

            [DllImport(DLL, CallingConvention = CallingConvention.Cdecl)] public unsafe static extern LinkRemoteTwinCATBuilderPtr AUTDLinkRemoteTwinCATWithTimeout(LinkRemoteTwinCATBuilderPtr twincat, ulong timeoutNs);

            [DllImport(DLL, CallingConvention = CallingConvention.Cdecl)] public unsafe static extern LinkBuilderPtr AUTDLinkRemoteTwinCATIntoBuilder(LinkRemoteTwinCATBuilderPtr twincat);
        }
    }

    [StructLayout(LayoutKind.Sequential)]
    public struct LinkTwinCATBuilderPtr
    {
        public IntPtr _0;
    }

    [StructLayout(LayoutKind.Sequential)]
    public struct LinkRemoteTwinCATBuilderPtr
    {
        public IntPtr _0;
    }

}

#if UNITY_2020_2_OR_NEWER
#nullable disable
#endif


