[workspace]

members = [
    "autd3",
    "autd3-core",
    "autd3-driver",
    "autd3-examples",
#    "autd3-gain-holo",
    "autd3-link-simulator",
    "autd3-link-soem",
    "autd3-link-twincat",
    "autd3-traits",
    "autd3-firmware-emulator",
    "autd3-modulation-audio-file",
]
