[package]
name = "sample"
version = "9.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.66"
autd3 = "9.0.0"
autd3-link-soem = "9.0.0"
