#pragma once

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <cstdint>

namespace autd3::internal::native_methods {

extern "C" {

[[nodiscard]] void* AUTDLinkTwinCAT();

[[nodiscard]] void* AUTDLinkTwinCATTimeout(void* builder, uint64_t timeout_ns);

[[nodiscard]] void* AUTDLinkTwinCATBuild(void* builder, char *err);

[[nodiscard]] void* AUTDLinkRemoteTwinCAT(const char *server_ams_net_id);

[[nodiscard]] void* AUTDLinkRemoteTwinCATServerIP(void* builder, const char *addr);

[[nodiscard]] void* AUTDLinkRemoteTwinCATClientAmsNetId(void* builder, const char *id);

[[nodiscard]] void* AUTDLinkRemoteTwinCATTimeout(void* builder, uint64_t timeout_ns);

[[nodiscard]] void* AUTDLinkRemoteTwinCATBuild(void* builder, char *err);

} // extern "C"

} // namespace autd3::internal::native_methods
