#pragma once

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <cstdint>

namespace autd3::internal::native_methods {

extern "C" {

void* AUTDGeometryViewer();

void* AUTDGeometryViewerSize(void* viewer, uint32_t width, uint32_t height);

void* AUTDGeometryViewerVsync(void* viewer, bool vsync);

int32_t AUTDGeometryViewerRun(void* viewer, void* cnt);

} // extern "C"

} // namespace autd3::internal::native_methods
