#pragma once

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <cstdint>

namespace autd3::internal::native_methods {

extern "C" {

[[nodiscard]] BackendPtr AUTDCUDABackend(char *err);

void AUTDCUDABackendDelete(BackendPtr backend);

[[nodiscard]]
GainPtr AUTDGainHoloCUDASDP(BackendPtr backend,
                            const double *points,
                            const double *amps,
                            uint64_t size);

[[nodiscard]] GainPtr AUTDGainHoloCUDASDPWithConstraint(GainPtr holo, ConstraintPtr constraint);

[[nodiscard]] GainPtr AUTDGainHoloCUDASDPWithAlpha(GainPtr holo, double alpha);

[[nodiscard]] GainPtr AUTDGainHoloCUDASDPWithLambda(GainPtr holo, double lambda);

[[nodiscard]] GainPtr AUTDGainHoloCUDASDPWithRepeat(GainPtr holo, uint32_t repeat);

[[nodiscard]]
GainPtr AUTDGainHoloCUDAEVP(BackendPtr backend,
                            const double *points,
                            const double *amps,
                            uint64_t size);

[[nodiscard]] GainPtr AUTDGainHoloCUDAEVPWithConstraint(GainPtr holo, ConstraintPtr constraint);

[[nodiscard]] GainPtr AUTDGainHoloCUDAEVPWithGamma(GainPtr holo, double gamma);

[[nodiscard]]
GainPtr AUTDGainHoloCUDAGS(BackendPtr backend,
                           const double *points,
                           const double *amps,
                           uint64_t size);

[[nodiscard]] GainPtr AUTDGainHoloCUDAGSWithConstraint(GainPtr holo, ConstraintPtr constraint);

[[nodiscard]] GainPtr AUTDGainHoloCUDAGSWithRepeat(GainPtr holo, uint32_t repeat);

[[nodiscard]]
GainPtr AUTDGainHoloCUDAGSPAT(BackendPtr backend,
                              const double *points,
                              const double *amps,
                              uint64_t size);

[[nodiscard]] GainPtr AUTDGainHoloCUDAGSPATWithConstraint(GainPtr holo, ConstraintPtr constraint);

[[nodiscard]] GainPtr AUTDGainHoloCUDAGSPATWithRepeat(GainPtr holo, uint32_t repeat);

[[nodiscard]]
GainPtr AUTDGainHoloCUDANaive(BackendPtr backend,
                              const double *points,
                              const double *amps,
                              uint64_t size);

[[nodiscard]] GainPtr AUTDGainHoloCUDANaiveWithConstraint(GainPtr holo, ConstraintPtr constraint);

[[nodiscard]]
GainPtr AUTDGainHoloCUDAGreedy(const double *points,
                               const double *amps,
                               uint64_t size);

[[nodiscard]] GainPtr AUTDGainHoloCUDAGreedyWithConstraint(GainPtr holo, ConstraintPtr constraint);

[[nodiscard]] GainPtr AUTDGainHoloCUDAGreedyWithPhaseDiv(GainPtr holo, uint32_t div);

[[nodiscard]]
GainPtr AUTDGainHoloCUDALM(BackendPtr backend,
                           const double *points,
                           const double *amps,
                           uint64_t size);

[[nodiscard]] GainPtr AUTDGainHoloCUDALMWithConstraint(GainPtr holo, ConstraintPtr constraint);

[[nodiscard]] GainPtr AUTDGainHoloCUDALMWithEps1(GainPtr holo, double eps);

[[nodiscard]] GainPtr AUTDGainHoloCUDALMWithEps2(GainPtr holo, double eps);

[[nodiscard]] GainPtr AUTDGainHoloCUDALMWithTau(GainPtr holo, double tau);

[[nodiscard]] GainPtr AUTDGainHoloCUDALMWithKMax(GainPtr holo, uint32_t k_max);

[[nodiscard]]
GainPtr AUTDGainHoloCUDALMWithInitial(GainPtr holo,
                                      const double *initial_ptr,
                                      uint64_t len);

} // extern "C"

} // namespace autd3::internal::native_methods
