#pragma once

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <cstdint>

namespace autd3::internal::native_methods {

extern "C" {

[[nodiscard]] ResultModulation AUTDModulationWav(const char *path);

[[nodiscard]]
ModulationPtr AUTDModulationWavWithSamplingConfig(ModulationPtr m,
                                                  SamplingConfiguration config);

[[nodiscard]] ResultModulation AUTDModulationRawPCM(const char *path, uint32_t sample_rate);

[[nodiscard]]
ModulationPtr AUTDModulationRawPCMWithSamplingConfig(ModulationPtr m,
                                                     SamplingConfiguration config);

} // extern "C"

} // namespace autd3::internal::native_methods
