#pragma once

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <cstdint>

namespace autd3::internal::native_methods {

struct GeometryViewerPtr {
  void* _0;
};

extern "C" {

[[nodiscard]] GeometryViewerPtr AUTDGeometryViewer();

[[nodiscard]]
GeometryViewerPtr AUTDGeometryViewerWithSize(GeometryViewerPtr viewer,
                                             uint32_t width,
                                             uint32_t height);

[[nodiscard]] GeometryViewerPtr AUTDGeometryViewerWithVsync(GeometryViewerPtr viewer, bool vsync);

[[nodiscard]] int32_t AUTDGeometryViewerRun(GeometryViewerPtr viewer, GeometryPtr geometry);

} // extern "C"

} // namespace autd3::internal::native_methods
