#pragma once

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <cstdint>

namespace autd3::internal::native_methods {

extern "C" {

[[nodiscard]] void* AUTDModulationWav(const char *path, char *err);

} // extern "C"

} // namespace autd3::internal::native_methods
