#pragma once

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <cstdint>

namespace autd3::internal::native_methods {

constexpr const uint32_t NUM_TRANS_IN_UNIT = 249;

constexpr const uint32_t NUM_TRANS_IN_X = 18;

constexpr const uint32_t NUM_TRANS_IN_Y = 14;

constexpr const uint32_t FPGA_CLK_FREQ = 163840000;

constexpr const uint32_t FPGA_SUB_CLK_FREQ = 20480000;

constexpr const int32_t AUTD3_ERR = -1;

constexpr const int32_t AUTD3_TRUE = 1;

constexpr const int32_t AUTD3_FALSE = 0;

enum class GainSTMMode : uint8_t {
  PhaseDutyFull = 0,
  PhaseFull = 1,
  PhaseHalf = 2,
};

enum class Level : uint8_t {
  Critical = 0,
  Error = 1,
  Warn = 2,
  Info = 3,
  Debug = 4,
  Trace = 5,
  Off = 6,
};

enum class TimerStrategy : uint8_t {
  Sleep = 0,
  NativeTimer = 1,
  BusyWait = 2,
};

enum class TransMode : uint8_t {
  Legacy = 0,
  Advanced = 1,
  AdvancedPhase = 2,
};

struct ControllerPtr {
  void* _0;
};

struct GeometryPtr {
  void* _0;
};

struct ModulationPtr {
  void* _0;
};

struct GainPtr {
  void* _0;
};

struct LinkPtr {
  void* _0;
};

struct DatagramBodyPtr {
  void* _0;
};

struct DatagramHeaderPtr {
  void* _0;
};

struct DatagramSpecialPtr {
  void* _0;
};

struct STMPropsPtr {
  void* _0;
};

constexpr const double TRANS_SPACING_MM = 10.16;

constexpr const double DEVICE_HEIGHT_MM = 151.4;

constexpr const double DEVICE_WIDTH_MM = 192.0;

} // namespace autd3::internal::native_methods
