#pragma once

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <cstdint>

namespace autd3::internal::native_methods {

constexpr const uint32_t NUM_TRANS_IN_UNIT = 249;

constexpr const uint32_t NUM_TRANS_IN_X = 18;

constexpr const uint32_t NUM_TRANS_IN_Y = 14;

constexpr const uint32_t FPGA_CLK_FREQ = 20480000;

constexpr const int32_t AUTD3_ERR = -1;

constexpr const int32_t AUTD3_TRUE = 1;

constexpr const int32_t AUTD3_FALSE = 0;

enum class GainSTMMode : uint8_t {
  PhaseDutyFull = 0,
  PhaseFull = 1,
  PhaseHalf = 2,
};

enum class TimerStrategy : uint8_t {
  Sleep = 0,
  BusyWait = 1,
  NativeTimer = 2,
};

struct ControllerPtr {
  void* _0;
};

struct ConstraintPtr {
  void* _0;
};

struct DevicePtr {
  void* _0;
};

struct TransducerPtr {
  void* _0;
};

struct GeometryPtr {
  void* _0;
};

struct ModulationPtr {
  void* _0;
};

struct GainPtr {
  void* _0;
};

struct LinkPtr {
  void* _0;
};

struct DatagramPtr {
  void* _0;
};

struct DatagramSpecialPtr {
  void* _0;
};

struct STMPropsPtr {
  void* _0;
};

struct BackendPtr {
  void* _0;
};

struct GroupGainMapPtr {
  void* _0;
};

struct LinkBuilderPtr {
  void* _0;
};

struct ResultI32 {
  int32_t result;
  uint32_t err_len;
  void* err;
};

struct ResultModulation {
  ModulationPtr result;
  uint32_t err_len;
  void* err;
};

struct ResultBackend {
  BackendPtr result;
  uint32_t err_len;
  void* err;
};

struct ResultController {
  ControllerPtr result;
  uint32_t err_len;
  void* err;
};

struct ResultGainCalcDrivesMap {
  void* result;
  uint32_t err_len;
  void* err;
};

constexpr const double TRANS_SPACING_MM = 10.16;

constexpr const double DEVICE_HEIGHT_MM = 151.4;

constexpr const double DEVICE_WIDTH_MM = 192.0;

constexpr const double ULTRASOUND_FREQUENCY = 40000.0;

extern "C" {

void AUTDGetErr(void* src, char *dst);

} // extern "C"

} // namespace autd3::internal::native_methods
