#pragma once

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <cstdint>

namespace autd3::internal::native_methods {

extern "C" {

[[nodiscard]] LinkPtr AUTDLinkTwinCAT(char *err);

[[nodiscard]] LinkPtr AUTDLinkTwinCATTimeout(LinkPtr twincat, uint64_t timeout_ns);

[[nodiscard]] LinkPtr AUTDLinkRemoteTwinCAT(const char *server_ams_net_id, char *err);

[[nodiscard]] LinkPtr AUTDLinkRemoteTwinCATServerIP(LinkPtr twincat, const char *addr);

[[nodiscard]] LinkPtr AUTDLinkRemoteTwinCATClientAmsNetId(LinkPtr twincat, const char *id);

[[nodiscard]] LinkPtr AUTDLinkRemoteTwinCATTimeout(LinkPtr twincat, uint64_t timeout_ns);

} // extern "C"

} // namespace autd3::internal::native_methods
