[package]
name = "capi_header_parser"
version = "10.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.57"
syn = { version = "2.0.16", features = ["parsing", "full"] }
serde = "1.0"
serde_derive = "1.0"
toml = "0.7.4"
