[package]
name = "capi_header_parser"
version = "2.7.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.57"
glob = "0.3.0"
regex = "1.5.6"

[features]
default = []
single_float = []
