[package]
name = "autd3-modulation-audio-file"
version = "10.0.0"
authors = ["shun suzuki <suzuki@hapis.k.u-tokyo.ac.jp>"]
edition = "2021"

license-file = "LICENSE"
description = "AUTD library for Rust."
repository = "https://github.com/shinolab/autd3"
readme = "../README.md"
keywords = ["autd"]

[dependencies]
hound = "3.5.0"
autd3-core = {path="../autd3-core", version="10.0.0"}
autd3-traits = {path="../autd3-traits", version="10.0.0"}
