name: build-nim

on:
  push:
    tags-ignore:
      - v*
    branches:
      - 'dev'

jobs:
  test:
    name: build test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v3
      - uses: jiro4989/setup-nim-action@v1
      - name: Build Package
        if: matrix.os == 'windows-latest'
        run: |
          cd ./nim
          nimble c src/autd3.nim
          Get-ChildItem -Path ./src/autd3/*.nim  | Resolve-Path -Relative | ForEach-Object { nimble c $_ }  
      - name: Build Package
        if: matrix.os != 'windows-latest'
        run: |
          cd ./nim
          nimble c src/autd3.nim
          find src/autd3 -maxdepth 1 -name '*.nim' -exec nimble c {} \;
