name: Release Check

on:
  push:
    tags-ignore:
      - v*
    branches:
      - 'release'


jobs:
  build:
    name: build ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v3
    - name: Build src on ${{ matrix.os }}
      run: |
        cd src
        cargo build --all
        cargo test --all 
    - name: Build examples on ${{ matrix.os }}
      run: |
        cd examples
        cargo build --all
        cargo test --all
    - name: Build capi on ${{ matrix.os }}
      run: |
        cd capi
        cargo build --all
        cargo test --all

  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: lint src
      run: |
        cd src
        cargo clippy --all -- -D warnings
    - name: lint examples
      run: |
        cd examples
        cargo clippy --all -- -D warnings
    - name: lint capi
      run: |
        cd src
        cargo clippy --all -- -D warnings
