name: Release Check

on:
  push:
    tags-ignore:
      - v*
    branches:
      - 'release'


jobs:
  build:
    name: build ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v3
    - uses: okazunori2013/cuda-toolkit@v0.3.6
      if: matrix.os != 'macos-latest'
    - name: Build src on ${{ matrix.os }}
      if: matrix.os == 'windows-latest'
      run: |
        cd src
        cargo build --all
        cargo test --workspace --exclude autd3-link-soem
        cargo clean
    - name: Build src on ${{ matrix.os }}
      if: matrix.os != 'windows-latest'
      run: |
        cd src
        cargo build --all
        cargo test --all
        cargo clean
    - name: Build examples on ${{ matrix.os }}
      if: matrix.os == 'windows-latest'
      run: |
        cd examples
        cargo build --bins --features "remote_soem twincat remote_twincat simulator_client simulator_server geometry_viewer" 
        cargo clean
    - name: Build examples on ${{ matrix.os }}
      if: matrix.os != 'windows-latest'
      run: |
        cd examples
        cargo build --bins --features "soem remote_soem twincat remote_twincat simulator_client simulator_server geometry_viewer" 
        cargo clean
    - name: Build capi on ${{ matrix.os }}
      if: matrix.os == 'windows-latest'
      run: |
        cd capi
        cargo build --all
        cargo test --workspace --exclude autd3capi-link-soem
        cargo clean
    - name: Build capi on ${{ matrix.os }}
      if: matrix.os != 'windows-latest'
      run: |
        cd capi
        cargo build --all
        cargo test --all
        cargo clean

  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: okazunori2013/cuda-toolkit@v0.3.6
    - name: lint src
      run: |
        cd src
        cargo clippy --all -- -D warnings
        cargo clean
    - name: lint examples
      run: |
        cd examples
        cargo clippy --all -- -D warnings
        cargo clean
    - name: lint capi
      run: |
        cd capi
        cargo clippy --all -- -D warnings
        cargo clean
